apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flask-app-logs-rwo
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-pvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app-pvc
  template:
    metadata:
      labels:
        app: flask-app-pvc
    spec:
      containers:
        - name: flask-app
          image: localhost:5000/k8s-workshop-app:debug
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: flask-app-config
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: flask-app-secret
                  key: DATABASE_URL
          volumeMounts:
            - name: app-logs
              mountPath: /data
      volumes:
        - name: app-logs
          persistentVolumeClaim:
            claimName: flask-app-logs-rwo
