apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-oom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app-oom
  template:
    metadata:
      labels:
        app: flask-app-oom
    spec:
      containers:
        - name: flask-app
          image: localhost:5000/k8s-workshop-app:debug
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: flask-app-config
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: flask-app-secret
                  key: DATABASE_URL
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 96Mi
