FROM python:3.12-slim
WORKDIR /workspace
COPY app/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY migrations/migrate.py /migrations/migrate.py
COPY migrations/sql /migrations/sql
CMD ["python", "/migrations/migrate.py"]
