apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration-broken
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migration
          image: localhost:5000/k8s-workshop-migration:broken
          imagePullPolicy: Always
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: flask-app-secret
                  key: DATABASE_URL
